# -*- coding: utf-8 -*-
"""LR_Analytical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Veve0VCoKqLuHPIRctx1V1jAT0k55zdi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("headbrain.csv")
df.shape
df.head()

X=df['Head Size(cm^3)'].values
y=df['Brain Weight(grams)'].values

mean_x=np.mean(X)
mean_y=np.mean(y)

print("Mean of X:",mean_x)
print("Mean of y:",mean_y)

numer=0
denom=0
n=len(X)
for i in range(n):
  numer+=(y[i]-mean_y)*(X[i]-mean_x)
  denom+=(X[i]-mean_x)**2
slope=numer/denom
intercept=mean_y-(slope*mean_x)

print("Slope:",slope)
print("Intercept:",intercept)
predictions=[]
for i in range(n):
  y_pred=slope*X[i]+intercept
  predictions.append(int(y_pred))

plt.figure(figsize=(10,6))
plt.scatter(X,y)
plt.plot(X,predictions,'r')
plt.show()

error=0
for i in range(n):
  error+=(predictions[i]-y[i])**2
mse=error/n
print("MSE:",mse)
print("RMSE:",np.sqrt(mse))