# -*- coding: utf-8 -*-
"""NLP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5U2WQCOoin-0_hTM2ExcJvpMpWR0IEy
"""

# Gradient Descent
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv("headbrain.csv")
df.shape
df.head()

X=df['Head Size(cm^3)'].values
y=df['Brain Weight(grams)'].values
n=len(X)

X=np.reshape(X,(-1,1))
y=np.reshape(y,(-1,1))
minmax=MinMaxScaler()
scaled_x=minmax.fit_transform(X)
scaled_y=minmax.fit_transform(y)

def gradient_descent(epochs, alpha):
  slope,inter=0,0
  for i in range(epochs):
    y_pred = scaled_x * slope + inter
    loss = y_pred - scaled_y
    gradSlope = (2/n) * np.dot(loss.T,scaled_x)
    gradInter = (2/n) * np.sum(loss)
    slope = slope - gradSlope * alpha
    inter = inter - gradInter * alpha
  return slope,inter
#hello
epochs = 10000
alpha = 0.01
slope,inter = gradient_descent(epochs,alpha)
print("Slope:",slope)
print("Intercept:",inter)

predictions=[]
for i in range(n):
  y_pred=slope[0][0]*scaled_x[i] + inter
  predictions.append(y_pred)

plt.figure(figsize=(10,6))
plt.scatter(scaled_x,scaled_y)
plt.plot(scaled_x,predictions,'g')
plt.show()

error=0
for i in range(n):
  error+=(predictions[i]-y[i])**2
mse=error/n
print("MSE:",mse)
print("RMSE:",np.sqrt(mse))
