# -*- coding: utf-8 -*-
"""GenAILR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOHndU61meK5xP4_QqPIGkc6CcAFnEHu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error

df = pd.read_csv("headbrain.csv")

X=df[['Head Size(cm^3)']]
y=df['Brain Weight(grams)']
model = LinearRegression()
model.fit(X,y)

y_pred = model.predict(X)

mse = mean_squared_error(y,y_pred)
rmse = np.sqrt(mse)

print("MSE ",mse)
print("RMSE ",rmse)

plt.figure(figsize=(10,10))
plt.scatter(X,y)
plt.plot(X,y_pred,'r')
plt.show()